name: development

on:
  push:
    branches:
      - "master"

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | AWK -f / '{print $2}' | sed -e "s/:refs//")
        shell: bash
      - uses: rlespinasse/github-slug-action@master
      - uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ahmedmahmoud25/flaskprivate
          tag: ${{ env.GIT_REF_SLUG}}
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}

