name: review

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get_version
        run: echo ::set-env name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - run: echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")
        shell: bash
      - uses: rlespinasse/github-slug-action@master
      - uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: ${{ env.REPOSITORY_NAME }}
          tag: ${{ env.GITHUB_REF_SLUG }}
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

